### ISSUE TITLE
The required library libhostfxr.so could not be found

### ISSUE THREAD

**Issue by CorruptComputer** [nickvdyck/cloudflare-ddns#4]
Followed the installation instructions in the README, but I couldn't get this working on a Raspberry Pi using the .NET 6 SDK.
I just wanted to check here to see if this was a known issue or if there is something on my end that needs changed.

```bash
pi@artemis:~ $ cloudflare-ddns -c /home/pi/cloudflare-config.json
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/pi/.dotnet/tools/.store/cloudflare-ddns/0.5.0/cloudflare-ddns/0.5.0/tools/net5.0/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=debian.11-arm64&apphost_version=6.0.1
pi@artemis:~ $ dotnet --version
6.0.101
```

The config I'm using is straight out of the README, just with my values subbed in (and extra `...` removed).

**Comment by vandycknick** [comment]
Sr for the late reply. But how did you install dotnet?

If you didn't use the conventional way to install dotnet you might need to point `DOTNET_ROOT` to the correct directory where dotnet is installed. Have a look here: https://github.com/dotnet/sdk/issues/9304#issuecomment-384911066

Also the tool wasn't really compatible with dotnet 6.0 yet. I'm pushing out a new version that should fix this.

**Comment by vandycknick** [comment]
The latest release now supports .net 6.0: https://github.com/vandycknick/cloudflare-ddns/releases/tag/v1.0.1

**Comment by CorruptComputer** [comment]
Hey there, apologies for the late reply as well its been quite a busy time for me lately.

The way I installed Dotnet was by using the method shown in the MSDN docs here: 
https://docs.microsoft.com/en-us/dotnet/iot/deployment

I'll download this latest version and see if I'm able to get it working now, thanks for the update!
